openapi: 3.0.0
info:
  title: Shopping Cart
  description: |
    This is a Shopping Cart API REST
  contact:
    email: leonardoicaraballo@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://virtserver.swaggerhub.com/leocaraballo/ShoppingCart/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8080/api
  description: API Entry Point Prefix
tags:
- name: products
  description: CRUD operations for the products
  externalDocs:
    description: Find out more
    url: http://localhost:8080/api/products
- name: users
  description: Operations about user
  externalDocs:
    description: Find out more
    url: http://localhost:8080/api/users
- name: shoppingcart
  description: Operations about the Shopping Cart
  externalDocs:
    description: Find out more
    url: http://localhost:8080/api/shoppingcart
- name: discount
  description: Operations concerning the discount and their respective product
  externalDocs:
    description: Find out more
    url: http://localhost:8080/api/discounts
paths:
  /products:
    get:
      tags:
      - products
      summary: Find all the Products in the store
      description: Returns all the products in the store
      operationId: getAllProducts
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                example:
                - id: 1
                  category:
                    id: 2
                    name: Electronics
                    description: Home appliances or digital devices
                  name: Smart TV 42'
                  price: 149.99
                  discounts: []
                  finalPrice: 149.99
                - id: 2
                  category:
                    id: 3
                    name: Groceries
                    description: Foods and drinks
                  name: Soda Cola 3L
                  price: 14.49
                  discounts: []
                  finalPrice: 14.49
                - id: 3
                  category:
                    id: 4
                    name: Music
                    description: Everything related to music
                  name: Generic Rap Songs
                  price: 11.49
                  discounts: []
                  finalPrice: 11.49
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
      - products
      summary: Create a new Product
      operationId: createProduct
      parameters:
      - name: categoryId
        in: query
        description: Id of the category of the new product
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              name: Smart TV 42'
              price: 149.99
      responses:
        200:
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: 1
                category:
                  id: 2
                  name: Electronics
                  description: Home appliances or digital devices
                name: Smart TV 42'
                price: 149.99
                discounts: []
                finalPrice: 149.99
  /products/find:
    get:
      tags:
      - products
      summary: Finds Product diverses query strings.
      operationId: getProductBy*
      parameters:
      - name: productName
        in: query
        description: Name of the Product to be searched
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: categoryId
        in: query
        description: Id of the category that the products belongs to
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: categoryName
        in: query
        description: name of the category that the products belongs to
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: containing
        in: query
        description: word thats contained in the name of the products searched
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/Product'
                - $ref: '#/components/schemas/Product'
              example:
              - id: 1
                category:
                  id: 2
                  name: Electronics
                  description: Home appliances or digital devices
                name: Smart TV 42'
                price: 149.99
                discounts: []
                finalPrice: 149.99
              - id: 3
                category:
                  id: 2
                  name: Electronics
                  description: Home appliances or digital devices
                name: New Phone X
                price: 449.99
                discounts: []
                finalPrice: 449.99
        404:
          description: Product Not Found or Category Not Found
  /products/{productId}:
    get:
      tags:
      - products
      summary: Finds Product by id.
      operationId: getProductById
      parameters:
      - name: productId
        in: path
        description: Id of the Product to be searched
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: 1
                category:
                  id: 2
                  name: Electronics
                  description: Home appliances or digital devices
                name: Smart TV 42'
                price: 149.99
                discounts: []
                finalPrice: 149.99
        404:
          description: Product Not Found
    put:
      tags:
      - products
      summary: Updates a Product
      operationId: replaceProduct
      parameters:
      - name: productId
        in: path
        description: Id of the Product to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Updated Product object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              name: Smart TV 42'
              price: 149.99
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: 1
                category:
                  id: 2
                  name: Electronics
                  description: Home appliances or digital devices
                name: Smart TV 42'
                price: 149.99
                discounts: []
                finalPrice: 149.99
        404:
          description: Product Not Found
    delete:
      tags:
      - products
      summary: Deletes a Product
      operationId: deleteProductById
      parameters:
      - name: productId
        in: path
        description: Id of the Product to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: boolean
        404:
          description: Product Not Found
  /products/categories:
    get:
      tags:
      - products
      summary: Find all the Categories
      description: Returns all the Categories
      operationId: getAllCategories
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                example:
                - id: 1
                  name: Commons
                  description: Default Category for all the items
                - id: 2
                  name: Electronics
                  description: Home appliances or digital devices
                - id: 3
                  name: Groceries
                  description: Foods and drinks
                - id: 4
                  name: Music
                  description: Everything related to music
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
      - products
      summary: Create a new Category
      operationId: createCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
            example:
              name: Electronics,
              description: Home appliances or digital devices
      responses:
        200:
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
              example:
                id: 1
                name: Electronics,
                description: Home appliances or digital devices
        409:
          description: Conflict, Category with input name already created
  /{productId}/category:
    put:
      tags:
      - products
      summary: Updates a Product category
      operationId: replaceCategory
      parameters:
      - name: productId
        in: path
        description: Id of the Product to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: categoryId
        in: query
        description: Id of the new category for the product
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Updated Product object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              name: Smart TV 42'
              price: 149.99
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: 1
                category:
                  id: 2
                  name: Electronics
                  description: Home appliances or digital devices
                name: Smart TV 42'
                price: 149.99
                discounts: []
                finalPrice: 149.99
        404:
          description: Product Not Found
  /users/login:
    get:
      tags:
      - users
      summary: Logs in a user
      operationId: login
      parameters:
      - name: username
        in: query
        description: Username of the user to be logged
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: Password of the user to be logged
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: succesful login
        400:
          description: bad request, incorrect password
  /users:
    get:
      tags:
      - users
      summary: Find all the Users
      description: Returns all the Users, could be filtered by query strings
      operationId: getAllUsers
      parameters:
      - name: lastName
        in: query
        description: Last Name of the Users to be searched
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: firstName
        in: query
        description: First Name of the Users to be searched
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                example:
                - id: 1
                  orders: []
                  firstName: Eamon
                  lastName: Andrew
                  username: eamondrew
                  password: password
                - id: 2
                  orders: []
                  firstName: Celine
                  lastName: Monaghan
                  username: celinee
                  password: asdf1234
                - id: 3
                  orders: []
                  firstName: Ivor
                  lastName: Andrew
                  username: theandrews
                  password: random64
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
      - users
      summary: Create a new User
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              firstName: Eamon
              lastName: Andrew
              username: eamondrew
              password: password
      responses:
        200:
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 1
                orders: []
                firstName: Eamon
                lastName: Andrew
                username: eamondrew
                password: password
        400:
          description: Bad Request, the username should only contain alphabetical characters.
        409:
          description: Conflict, the username entered is already in use.
  /users/{username}:
    get:
      tags:
      - users
      summary: Finds User by their username.
      operationId: getUserByUsername
      parameters:
      - name: username
        in: path
        description: Username of the User to be searched
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 1
                orders: []
                firstName: Eamon
                lastName: Andrew
                username: eamondrew
                password: password
        404:
          description: User Not Found
  /users/{userId}:
    get:
      tags:
      - users
      summary: Finds User by their Id.
      operationId: getUserById
      parameters:
      - name: userId
        in: path
        description: Id of the User to be searched
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 1
                orders: []
                firstName: Eamon
                lastName: Andrew
                username: eamondrew
                password: password
        404:
          description: User Not Found
    put:
      tags:
      - users
      summary: Updates a User
      operationId: replaceUser
      parameters:
      - name: userId
        in: path
        description: Id of the User to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: Updated User object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              firstName: Marty
              lastName: McFly
              password: back3
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: 1
                orders: []
                firstName: Marty
                lastName: McFly
                username: eamondrew
                password: back3
        400:
          description: Bad Request, cannot change the username of a User.
        404:
          description: User Not Found
    delete:
      tags:
      - users
      summary: Deletes a User
      operationId: deleteUserById
      parameters:
      - name: userId
        in: path
        description: Id of the User to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: boolean
        404:
          description: User Not Found
  /shoppingcart/{userId}:
    get:
      tags:
      - shoppingcart
      summary: Finds ShoppingCart by their User Id.
      operationId: getShoppingCartByUserId
      parameters:
      - name: userId
        in: path
        description: Id of the User to search their Shopping Cart
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShoppingCart'
              example:
                id: 1
                currentItems: []
                user:
                  id: 1
                  orders: []
                  firstName: Marty
                  lastName: McFly
                  username: eamondrew
                  password: back3
        404:
          description: User Not Found
    post:
      tags:
      - shoppingcart
      summary: Add a OrderLine to the ShoppingCart, with a Product Id and quantity.
      operationId: addToCart
      parameters:
      - name: userId
        in: path
        description: Id of the User to search their Shopping Cart
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: productId
        in: query
        description: Id of the Product to be added to the Cart
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: quantity
        in: query
        description: Quantity of Product to be added
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderLine'
              example:
                id: 1
                product:
                  id: 1
                  name: Smart TV 42'
                  price: 149.99
                quantity: 3
        404:
          description: User Not found or Product Not Found
        409:
          description: Conflict, the product is already in the ShoppingCart
    delete:
      tags:
      - shoppingcart
      summary: Deletes a OrderLine from a ShoppingCart
      operationId: deleteFromCart
      parameters:
      - name: userId
        in: path
        description: Id of the User to search their Shopping Cart
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: orderLineId
        in: query
        description: Id of the OrderLine to be deleted
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: query
        description: Id of the Product contained in the OrderLine to be deleted
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: boolean
        404:
          description: User Not Found
  /api/shoppingcart/{userId}:
    get:
      tags:
      - shoppingcart
      summary: Finds OrderLine of a specific ShoppingCart
      operationId: getOrderLine
      parameters:
      - name: userId
        in: path
        description: Id of the User to search their Shopping Cart
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: orderLineId
        in: query
        description: Id of the OrderLine to be searched.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: query
        description: Id of the Product that the OrderLine to be searched contains.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderLine'
              example:
                id: 1
                product:
                  id: 1
                  name: Smart TV 42'
                  price: 149.99
                quantity: 3
        404:
          description: User Not Found or OrderLine Not Found
  /shoppingcart/{userId}/clear:
    delete:
      tags:
      - shoppingcart
      summary: Deletes all the OrderLine from a ShoppingCart
      operationId: clear
      parameters:
      - name: userId
        in: path
        description: Id of the User to clear their Shopping Cart
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
        404:
          description: User Not Found
  /shoppingcart/{userId}/checkout:
    post:
      tags:
      - shoppingcart
      summary: Creates an Order with the cart contents and then clears the ShoppingCart
      operationId: checkout
      parameters:
      - name: userId
        in: path
        description: Id of the User to check out their Shopping Cart
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              example:
                id: 1
                items:
                - id: 1
                  product:
                    id: 1
                    name: Smart TV 42'
                    price: 149.99
                  quantity: 3
                - id: 2
                  product:
                    id: 2
                    name: New Phone X
                    price: 450
                  quantity: 1
                timestamp: 2019-02-20T15:00:02.0548
        400:
          description: Bad request, can't check out a empty cart
        404:
          description: User Not Found
  /shoppingcart/{userId}/orders:
    get:
      tags:
      - shoppingcart
      summary: Finds the Orders of a User
      operationId: getUserOrders
      parameters:
      - name: userId
        in: path
        description: Id of the User to search their Shopping Cart
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: orderId
        in: query
        description: Id of the Order to search for
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                anyOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/Order'
                - $ref: '#/components/schemas/Order'
              example:
              - id: 1
                items:
                - id: 1
                  product:
                    id: 1
                    name: Smart TV 42'
                    price: 149.99
                  quantity: 3
                - id: 2
                  product:
                    id: 2
                    name: New Phone X
                    price: 450
                  quantity: 1
                timestamp: 2019-02-20T15:00:02.0548
              - id: 2
                items:
                - id: 1
                  product:
                    id: 1
                    name: LED TV 32'
                    price: 49
                  quantity: 1
                timestamp: 2019-02-20T15:00:02.0548
        404:
          description: User Not Found
components:
  schemas:
    Role:
      type: string
      enum:
      - Normal
      - Admin
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
      xml:
        name: Category
    Discount:
      type: object
      properties:
        id:
          type: integer
          format: int64
        percentage:
          type: number
        reason:
          type: string
      xml:
        name: Discount
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
        price:
          type: number
        discounts:
          type: array
          items:
            $ref: '#/components/schemas/Discount'
      xml:
        name: Product
    CartItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
          format: int32
      xml:
        name: CartItem
    OrderLine:
      type: object
      properties:
        id:
          type: integer
          format: int64
        product:
          $ref: '#/components/schemas/Product'
        quantity:
          type: integer
          format: int32
        cost:
          type: number
      xml:
        name: OrderLine
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderLine'
        timestamp:
          type: string
          format: date-time
      xml:
        name: Order
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        role:
          $ref: '#/components/schemas/Role'
        token:
          type: integer
          format: int64
        sessionStartTimestamp:
          type: string
          format: date-time
      xml:
        name: User
    ShoppingCart:
      type: object
      properties:
        id:
          type: integer
          format: int64
        currentItems:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        user:
          $ref: '#/components/schemas/User'
      xml:
        name: ShoppingCart
